### ISSUE TITLE
Warenkorb

### ISSUE THREAD

**Issue by AntonyPaok** [derechtenap/projekt-webshop#2]

**Comment by timderes** [comment]
Hat sich einer schon Gedanken zum Warenkorb gemacht?
Vielleicht als Array?

**Comment by EricVanDeGriesel** [comment]
- Produktdatenbank #4 

- Seite die alle Produkte anzeigt, die ausgewählt

- Bootstrap Modals/Toasts als kleine Übersicht rechts oben auf Seite
https://www.w3schools.com/bootstrap/bootstrap_modal.asp
https://www.w3schools.com/bootstrap4/bootstrap_toast.asp

- Zwischenspeicherung der Produkte in einer Session

- (Optional -> Warenkorb zu Kundenzuordnung)

- Produkte Entfernen/Verdoppeln

- (Optional ->Rabatt Funktion)

-

**Comment by timderes** [comment]
Mit 6c55fd9 ist dieses Issue fast fertig
