### ISSUE TITLE
Fehlende Seiten hinzufügen

### ISSUE THREAD

**Issue by timderes** [derechtenap/projekt-webshop#25]
**Folgende Seiten sind verlinkt auf dem Index und haben noch keine Seite:**

_Navbar_
- [x] Produkte und das dazugehörige Dropdown (`produkte\obst.php` etc.)
- [x] Neuheiten (`produkte/neuheiten.html`
- [x] Sale (`produkte/sale.html`)
- [x] Nutzer (`profil/nutzer.html`)
- [x] Über uns (`hilfe/ueber-uns.html`)
- [x] Hilfe (`hilfe/uebersicht.html`)

_Footer_
- [x] Kontakt (`kontakt/formular.php`)

_Sonstiges_
- [x] Button für Verlinkung vom Warenkorb zur Kasse

**Comment by timderes** [comment]
Damit der Issue nicht falsch verstanden wird: Ich mache für die meisten Seiten nur ganz schnelle Blender. Nur damit der Shop nicht in einen 404-Fehler läuft...

**Comment by timderes** [comment]
@AntonyPaok wollte die Sale und Neuheiten Seite machen. Ich kann nachher auch noch etwas über das Frontend gucken

**Comment by EricVanDeGriesel** [comment]
- [ ] Button für Verlinkung vom Warenkorb zur Kasse

**Comment by timderes** [comment]
Mit #52 wurden die Produktseiten hinzugefügt
