### ISSUE TITLE
Modal funktioniert nicht mit "Paprika bunt"

### ISSUE THREAD

**Issue by timderes** [derechtenap/projekt-webshop#26]
Beim klicken auf die Card von Paprika bunt kommt diese Fehlermeldung:

`Uncaught TypeError: Illegal invocation at Object.findOne (selector-engine.js:28) at new t (modal.js:87) at HTMLAnchorElement.<anonymous> (modal.js:591) at HTMLDocument.i (event-handler.js:116)`

Das liegt höchstwahrscheinlich am **Leerzeichen** im Datenbank-Eintrag. Wir sollten das Produkt umbenennen oder aus dem Sortiment nehmen, @AntonyPaok 😏

**Comment by AntonyPaok** [comment]
Auch erledigt #32
