### ISSUE TITLE
Spaltennamen der DB

### ISSUE THREAD

**Issue by timderes** [derechtenap/projekt-webshop#27]
Mir ist gerade aufgefallen, dass einige Spalten der DB in Englisch und andere in Deutsch sind. Zusätzlich beginnen einige mit einem Großbuchstaben. Die Lagerbestand-Spalte hat auch einen Tippfehler. Wir sollten das optimieren:

- [x] Spalten in der DB umbenennen
- [x] Variablen innerhalb der PHP Dateien anpassen

**Comment by AntonyPaok** [comment]
Kategorien der Produkte
Kartoffelsalat und Snadwich raus
ß bei Eisweß weg

**Comment by AntonyPaok** [comment]
Fixes #32

**Comment by AntonyPaok** [comment]
Erledigt. Siehe #32
