### ISSUE TITLE
Liste mit Lebensmittel

### ISSUE THREAD

**Issue by AntonyPaok** [derechtenap/projekt-webshop#3]
Beinhalten ein Bild, Titel/ Name, Preis, Fehlerstatus bzw. Verfügbarkeit, Eingabe für Menge und Button "In den Warenkorb"

**Comment by timderes** [comment]
Was genau ist mit Liste gemeint?

**Comment by EricVanDeGriesel** [comment]
- Zugriff auf Datenbank für Produktinformationen

- Bilder in separaten Ordner

- Tabellenansicht -> Zeilenweise Anordnung der Produkte

**Comment by AntonyPaok** [comment]
Wir müssen noch entscheiden, wie genau das aussehen soll und welche Daten zu sehen sind.
Eine Idee wäre die Hintergrundfarbe bei der Schrift mit der Kategorie-Farbe gleich zu machen.
Meine Idee wäre, dass wenn man auf die Cards drückt, sich die Tabelle mir den Nährwerten öffnet. Dafür soll ein Button "In den Warenkorb" erstellt werden. 
@derechtenap ist es wegen diesem Model möglich bzw. mit wenig Aufwand so umsetzbar ?

**Comment by timderes** [comment]
Ich lade hier gleich oder morgen mal eine Preview für die Liste hoch @AntonyPaok 👍

**Comment by timderes** [comment]
Hab einen PR erstellt (#23). Ihr könnt euch den Code ja mal ansehen und vielleicht etwas Feedback geben. Ein paar Notizen hab ich auch mal in #23 aufgeschrieben

@EricVanDeGriesel @AntonyPaok
