### ISSUE TITLE
Carousel Hintergrundbilder sind immer noch Platzhalter

### ISSUE THREAD

**Issue by timderes** [derechtenap/projekt-webshop#30]
Leider waren die Bilder der Produkte **zu klein** für das Carousel... Deswegen hab ich noch einmal schnelle **Platzhalter** erstellt. Wir brauchen größere und höher aufgelöste Bilder von den Produkten.

**@AntonyPaok Kannst du vielleicht noch ein paar Bilder machen? Am besten mit einen einheitlichen Hintergrund (z.B. Komplett grau etc.)**

Aktuell hab ich diese Hintergrundbilder fürs Carousel:

![1](https://user-images.githubusercontent.com/50623315/89637271-37c63d00-d8aa-11ea-8a1f-be8bffc2f52f.jpg)
![2](https://user-images.githubusercontent.com/50623315/89637277-38f76a00-d8aa-11ea-83ec-eb7c5997dacf.jpg)
![3](https://user-images.githubusercontent.com/50623315/89637278-39900080-d8aa-11ea-8e59-c631d797bd38.jpg)

**Comment by AntonyPaok** [comment]
Die neuen Bilder, für die neuen Produkte hab ich größer gelassen. Hintergrund ist immer einheitlich dieses "graue-Holz".
Ich hoffe das ist so in Ordnung. Die "alten" Bilder habe ich auch in original Größe. Brauchst du auch diese?

**Comment by timderes** [comment]
Ne, die neuen reichen. Damit sollte ich was fürs Carousel erstellen können 👍
