### ISSUE TITLE
Datenbank

### ISSUE THREAD

**Issue by AntonyPaok** [derechtenap/projekt-webshop#4]
Beinhaltet Lebensmittel und Preise und zeigt die Verfügbarkeit an.
Ist Datenbasis für die Liste der Lebensmittel

**Comment by timderes** [comment]
Sollen Kundendaten auch gespeichert werden?

**Comment by EricVanDeGriesel** [comment]
- Datenbankeinträge in JSON Objekt umwandeln

[Mappe2.xlsx](https://github.com/derechtenap/projekt-webshop/files/4941591/Mappe2.xlsx)

**Comment by EricVanDeGriesel** [comment]
Kundendatenbank nötig

Bestelldatenbank nötig

**Comment by AntonyPaok** [comment]
Ich habe mich mal mit den Datenbankentwurf auseinandergesetzt... das war mega kompliziert...so sollten alle Funktionen kein Problem machen.
[DB Entwurf Webshop.pdf](https://github.com/derechtenap/projekt-webshop/files/4948900/DB.Entwurf.Webshop.pdf)

**Comment by timderes** [comment]
Das sieht echt professionell aus 👍😊

**Comment by AntonyPaok** [comment]
Funktionsmäßig müsste die DB komplett sein. Die ist auch in dieser Hosting Seite. Die ersten Produkte sind auch schon drin. Alle anderen Tabellen sollten ja im Idealfall durch die Webseite gefüllt werden. Also wenn man sich einloggt, dann entsteht ein Eintrag in T_Kunde, wenn man bestellt entsteht einer in T_Bestelliste und T_Rechnung. Wenn ihr auch der Meining seit, dann haben wir unseren ersten Issue geschlossen xD 

Eine Übersicht ist beigefügt:
[d03316a7.pdf](https://github.com/derechtenap/projekt-webshop/files/4960410/d03316a7.pdf)

**Comment by AntonyPaok** [comment]
Datenbank soweit komplett. 
Siehe #19
