### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by AntonyPaok** [derechtenap/projekt-webshop#5]
- Ein paar Worte zu "wer wir sind"
- Neuigkeiten (Art schwarzes Brett)
- Allgemeine Hinweise zu Zahlungsmöglichkeiten, Lieferbedingungen etc.

**Comment by timderes** [comment]
Wollte das Design bisschen vom Nike Shop übernehmen

[Siehe hier](https://www.nike.com/de/)

**Comment by timderes** [comment]
Das ist der aktuelle Stand der Startseite: 
![image](https://user-images.githubusercontent.com/50623315/87852012-89f4ed80-c8fe-11ea-8f6c-5f178a5ba13f.png)

**Comment by EricVanDeGriesel** [comment]
> Das ist der aktuelle Stand der Startseite:

Startseite:
Cards dienen als Kategorien Übersicht (Anlehnung an Rewe Shop)
https://shop.rewe.de/?ecid=sea_google_ls_brands_[tmk-0001|bm|ls]_rewe-kaufen-[tmk-0001|eco-0012|1|bm|ls]_text-ad_773169730_40845292245&gclid=Cj0KCQjwu8r4BRCzARIsAA21i_DLVMOEDRZ746JIRFPUMI757XgEDsK38kEOxe6l63_a39k0CkUBoDAaAjIzEALw_wcB

Karoussel als Angebot Eyecatcher und Neuigkeitenübermittler

**Comment by timderes** [comment]
Im Branch frontend-dev hab ich eine aktualisierte Version der Seite hochgeladen. Hab die Kategorien und deren Cards mal verbessert. Hier ein Preview:
![image](https://user-images.githubusercontent.com/50623315/88186376-5fc06a00-cc35-11ea-9030-e27f549a5c4f.png)

Was haltet ihr von den Farben? Habt ihr noch Ideen? 😃

**Comment by AntonyPaok** [comment]
- Wenn ich mich nicht irre, wollten wir als Kategorien uns an Rewe halten..oder? Oder wollten wir nur Obst und Gemüse anbieten? 
- Zu den Farben würde ich persönlich sagen, dass wir etwas hellere/ knalligere Farben brauchen für Lebensmittel und vor allem für Früchte und Obst, also Farben nehmen die das Gemüse und Obst tatsächlich auch haben. 
- Der Footer sieht von der Form Top aus! (Zu den Farben allgm. habe ich ja oben kommentiert)

**Comment by timderes** [comment]
> Kategorien uns an Rewe halten..oder?

Die können ja noch hinzugefügt werden 😄 

> hellere/ knalligere Farben

Ja, das sind die aktuellen Standardfarben von BS. Wie findest du [diese Farben](https://flatuicolors.com/palette/au)?
![image](https://user-images.githubusercontent.com/50623315/88210991-4fb88280-cc55-11ea-857b-32e424e4e242.png)

> Der Footer sieht von der Form Top aus! (Zu den Farben allgm. habe ich ja oben kommentiert)

Das dunkle Design des Footers würde ich beibehalten. Es gibt einen guten Kontrast und Abschluss

**Comment by AntonyPaok** [comment]
> Ja, das sind die aktuellen Standardfarben von BS. Wie findest du [diese Farben](https://flatuicolors.com/palette/au)?
> ![image](https://user-images.githubusercontent.com/50623315/88210991-4fb88280-cc55-11ea-857b-32e424e4e242.png)

Die finde ich auf jeden Fall passender :D 

> Das dunkle Design des Footers würde ich beibehalten. Es gibt einen guten Kontrast und Abschluss

Ja wenn alles fertig ist macht das vlt mehr Sinn...jetzt ist ja alles grau :D

**Comment by timderes** [comment]
Müssen mal die Platzhalter mit richtigen Bildern ersetzen 😊 Glaube dann wirkt das schon ganz anders. Hab die Navigation mal mit anderen Farben probiert... Aber das wirkte irgendwie komisch. Die Grautöne waren besser und wirkten edler 🤔😅

**Comment by AntonyPaok** [comment]
Ja die Farbe ist ja wohl keine große Sache...am Ende können wir ja alle einen Blick drüber werfen :D

**Comment by timderes** [comment]
**Änderungen damit dieser Issue geschlossen werden kann:**
- [x] Links setzen
- [x] Bilder im Karussell
- [x] Modal Fullscreen --> Seite nur für Testzwecke... etc.

**Comment by timderes** [comment]
Alles soweit fertig. Nur #30 müsste vielleicht noch erledigt werden.
