### ISSUE TITLE
Bestellvorgang

### ISSUE THREAD

**Issue by AntonyPaok** [derechtenap/projekt-webshop#6]
- Evtl. nur Bestellungen ohne Registrieren um den Rahmen nicht zu sprengen (als Gast)
- Eingabe von Rechnungs- und Lieferadresse
- Evtl. nur Überweisung um Komlexitätslevel gering zu halten ?

Navigation wie üblich
Am Ende eine Übersicht und ein Button"zahlungspflichtig bestellen"
Meldung: "Bestellung erfolgreich" (wenn einfach, random BestellNr. erzeugen und anzeigen)

**Comment by timderes** [comment]
> wenn einfach, random BestellNr. erzeugen und anzeigen

Eigentlich können wir hier auch eine Bestell-ID aus der DB nehmen

**Comment by EricVanDeGriesel** [comment]
1. Vom Warenkorb zur Login Seite.
- Zwei Möglichkeiten:
a Nutzer hat bereits Account
b Nutzer muss Account erstellen

2. Zahlungsmöglichkeiten/ Lieferadresse/ Versand

3. Übersicht + Zahlungspflichtig bestellen

**Comment by EricVanDeGriesel** [comment]
Optional E-Mail Bestätigung der Bestellung

**Comment by timderes** [comment]
[Branch](https://github.com/derechtenap/projekt-webshop/tree/warenkorb-test) zum Issue

**Comment by EricVanDeGriesel** [comment]
![Übersicht](https://user-images.githubusercontent.com/55184120/89538658-240fcd80-d7fb-11ea-9878-932db924df13.png)
@derechtenap

**Comment by EricVanDeGriesel** [comment]
Aktuelle Problematik bzw. Komplexität:
Abbildung der Produkte im Checkout bzw. in der Bestelluebersicht. Da sollen ja die Produkte + Menge + Preis untereinander angegeben werden und eine Summe gebildet werden. Vllt kann man das Skript vom Warenkorb teilweise verwenden. Bin da aber aktuell am struggeln.

**Comment by EricVanDeGriesel** [comment]
Die Produktnamen in der DB sollten den präfix artikel_ bekommen und das product an sich sollte kleingeschrieben sein. Außer das löst konflikte mit euren Code haben.

**Comment by timderes** [comment]
Hatte ich nicht diesen Prefix bei mir hinzugefügt? Also `_artikel`? Eigentlich müsste das doch dann bei dir auch seien. Wollten das doch über den localStorage machen.

**Comment by EricVanDeGriesel** [comment]
der nettopreis wird ja nicht im localstorage gespeichert. den brauche ich aber, um den Preis zu ermitteln. im aktuellen warenkorb ist so eine auflistung ja auch nicht vorhanden

**Comment by timderes** [comment]
Mein Code müsste auch mit kleingeschriebenen Artikeln funktionieren 🤔

**Comment by timderes** [comment]
Könnten über die `produkte .php` den Nettopreis in den localStorage laden

**Comment by EricVanDeGriesel** [comment]
es gibt ja aktuell zwei spalten in der DB bei Produkte. Einmal Produkt_Name und einmal Anzeige_Name. Kann Produkt_Name bspw. "artikel_tomate" (also gleich dem localstorage key) heißen oder ist das ein problem ?

**Comment by EricVanDeGriesel** [comment]
Localstorage to Datenbank -> @AntonyPaok

**Comment by EricVanDeGriesel** [comment]
Sieht sehr gut aus, Danke ! 
Sind die Divs, wo die Daten nochmals dargestellt werden auch schon bearbeitet ?

**Comment by timderes** [comment]
> Sind die Divs, wo die Daten nochmals dargestellt werden auch schon bearbeitet ?

Ja, die benutzen das Container-Layout der Adressen. Mit richtigen Daten und Eingabe können wir das aber noch etwas verbessern (Wenn nötig 😄 )

**Comment by timderes** [comment]
Wenn noch irgendwas geändert werden soll oder du auf Probleme stößt, kannst du mir gerne schreiben

**Comment by EricVanDeGriesel** [comment]
Ja ein "Fehler" ist mir aufgefallen: Und zwar ist den Input Type bei "PLZ" ein Auswahlfeld bzw. so ein Hochzähl dingen. Glaube normales Textfeld würde reichen

**Comment by timderes** [comment]
Stimmt, das kommt weil ich den `type` auf `number` geändert hab. Hielt das für passender... Aber das ist natürlich da nicht so vorteilhaft. Mal gucken ob man das irgendwie wegkriegt...

**Edit:** Hab einen Fix gefunden... Mache einen Commit

**Comment by timderes** [comment]
Hab den Warenkorb noch schnell gemacht
