### ISSUE TITLE
Kontaktformular

### ISSUE THREAD

**Issue by AntonyPaok** [derechtenap/projekt-webshop#7]
Eingabefelder und Freitext

**Comment by AntonyPaok** [comment]
Wenn das Kontaktformular funktionieren soll und nicht nur ein Blender wird, kommt bei uns eine E-Mail unter info@nextlvlgoods.de an und automatisch wird eine E-Mail an den Kunden verschickt (diese Funktion bietet all-ink-an). Wir müssen nur dafür sorgen, dass mit dem "Abschicken" - Button im Formular eine E-Mail an die "info@..." geschickt wird.

**Comment by timderes** [comment]
Wir könnten das dann mit [mailto](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks#E-mail_links). Also mehr oder weniger einen dynamischen Link erzeugen. Das geht relativ einfach und dann vielleicht sogar ohne PHP etc.

Das sieht dann ungefähr so aus: Subject könnte z.B. mit jQuery manipuliert werden (je nach Eingabe)
> a href="mailto:nowhere@mozilla.org?cc=name2@rapidtables.com&bcc=name3@rapidtables.com&subject=The%20subject%20of%20the%20email&body=The%20body%20of%20the%20email"

**Comment by AntonyPaok** [comment]
Hört sich ganz gut an

**Comment by timderes** [comment]
Ich denke mal wir sollten diesen Issue schließen... Da wir eh nicht mehr viel Zeit haben, oder? 

@AntonyPaok @EricVanDeGriesel
