### ISSUE TITLE
Impressum/ Anschrift

### ISSUE THREAD

**Issue by AntonyPaok** [derechtenap/projekt-webshop#8]
Zu der Anschrift evtl. noch Google Maps als "Iframe"

**Comment by timderes** [comment]
Welche Adresse nehmen wir dann? 😃

**Comment by timderes** [comment]
Ich arbeite jetzt an diesem Issue

**Comment by timderes** [comment]
Was mir gerade noch einfällt: Wenn wir wirklich den Shop online stellen wollen (auch wenn es nur für die kurze Präsentation der Funktionen ist), sind wir **nach Telemediengesetz (TMG) verpflichtet ein richtiges Impressum anzugeben**. Sonst kann man uns da ziemlich hart ans Bein pinkeln.

Ist mir gerade so eingefallen als 2,0er IT-Rechtler 😆 

[Link zum Telemediengesetz](https://www.bmjv.de/DE/Verbraucherportal/DigitalesTelekommunikation/Impressumspflicht/Impressumspflicht_node.html)

Was meint ihr? Wie sollen wir damit umgehen?
@AntonyPaok @EricVanDeGriesel
