### ISSUE TITLE
Organisatorisches

### ISSUE THREAD

**Issue by AntonyPaok** [derechtenap/projekt-webshop#9]
- Wer macht was? Wo sind Schnittstellen?
- Welche Sprache? Wie werden Daten verarbeitet?
- Wie ist es möglich, möglichst viele Themen der Veranstaltung auszubauen?
- Wo liegt unser Schwerpunkt?
- Was und wie viel muss dokumentiert werden?
- Termin vereinbaren für Vorstellung --> PP notwendig??

**Comment by timderes** [comment]
> Wer macht was? [...]

Würde wie gesagt, mich gerne ums Frontend kümmern

> Termin vereinbaren für Vorstellung --> PP notwendig??

Soll wohl nur eine kleine PP werden. Aber wir sollten eine machen

**Comment by EricVanDeGriesel** [comment]
>  Wie werden Daten verarbeitet?

Würde sagen, dass wir auf jeden Fall für Unser Projekt das MVVM Modell einführen. Wurde im Laufe des Moduls ja behandelt und ist ziemlich leicht zu realisieren.

**Comment by EricVanDeGriesel** [comment]
> Wie ist es möglich, möglichst viele Themen der Veranstaltung auszubauen?

Würde da sagen, wir Arbeiten ein Konzept aus und legen fest, welche Funktionen wir einbauen wollen. Je nachdem kann man Veranstaltungsinhalt einbauen. Beispielsweise können könnten wir, wie im vorherigen Comment schon gesagt, das MVVM Modell einbauen und Angular einbauen. 

> Wo liegt unser Schwerpunkt?

Glaube da wir eigentlich ziemlich breit gefächert sind was Skills angeht, würde ich sagen wir decken alles ab was wir können.
Vllt. noch interessant wäre es, etwas zu zu implementieren, was die Seite besonders macht.

**Comment by timderes** [comment]
> Glaube da wir eigentlich ziemlich breit gefächert sind was Skills angeht, würde ich sagen wir decken alles ab was wir können.
Vllt. noch interessant wäre es, etwas zu zu implementieren, was die Seite besonders macht.

Ja, also ich hab auch mit BS5 das Layout schon angefangen. Das geht ja auch recht schnell. Deswegen kann ich dann auch noch an zusätzlichen Sachen arbeiten

**Comment by timderes** [comment]
Eigentlich können wir den Issue schließen, oder? Falls nicht: Können wir den hier einfach wieder öffnen...
